site_name: Whiplash
docs_dir: docs
site_dir: libs/public/docs
theme: flatly
pages:
- Home: index.md
- Overview: overview.md
- Quick Start: quick_start.md
- Usage:
    - basic_usage.md
    - deployment_examples.md
    - application_examples.md
- Deployment: deployment.md
<!-- - Standards: standards.md -->
<!-- - Snapshot: snapshot.md -->
