odb:
    image: mongo:latest
    ports:
        - "27017:27017"

api:
    extends:
        file: ../../api/docker-compose.yml
        service: api
    ports:
        - "1337:1337"
    volumes:
        - ../../api/libs:/src/libs
        - ../../api/bin:/src/bin
    environment:
        MONGO_PORT_27017_TCP_ADDR: odb
        MONGO_PORT_27017_TCP_PORT: 27017
        MONGO_API_PASSWORD: password
    links:
        - odb:odb
    command: sh -c "node --use_strict bin/init_db; node --use_strict bin/create_user admin password admin@whiplash.ethz.ch; node --use_strict bin/create_user test test test@test.com; node --use_strict bin/api"

www:
    extends:
        file: ../../www/docker-compose.yml
        service: www
    ports:
        - "3000:3000"
    volumes:
        - ../../www/public:/src/public
        - ../../www/views:/src/views
        - ../../www/routes:/src/routes
    environment:
        WHIPLASH_API_HOST: api
        WHIPLASH_API_PORT: 1337
    links:
        - api:api
    restart: always
    command: sh -c "node --use_strict bin/www"

scheduler:
    extends:
        file: ../../scheduler/docker-compose.yml
        service: scheduler
    volumes:
        - ../../scheduler/bin:/src/bin
        - ../../scheduler/libs:/src/libs
        - /var/run/docker.sock:/var/run/docker.sock
        - $PWD:/input
    environment:
        WHIPLASH_HOST_WORK_DIR: $PWD
        WHIPLASH_LAUNCH_WORK_DIR: '/input'
        WHIPLASH_API_HOST: api
        WHIPLASH_API_PORT: 1337
        WHIPLASH_ADMIN_PASSWORD: password
    links:
        - api:api
    command: sh -c "sleep 20; node --use_strict bin/scheduler"
