before_script:
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - docker-compose -f develop.yml build
    - docker-compose -f develop.yml up -d
    - sleep 30
  tags:
    - docker

test:
  stage: test
  script:
    - export PYTHONPATH=$PWD/python:$PYTHONPATH
    - ./tests/pre-tests.py ${DOCKERHOST:-localhost} 1337
    - sleep 30
    - ./tests/post-tests.py ${DOCKERHOST:-localhost} 1337
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - docker-compose -f develop.yml stop
    - docker-compose -f develop.yml rm -f
  tags:
    - docker
