before_script:
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - docker-compose -f test.yml build
    - docker-compose -f test.yml up -d
    - sleep 15
  tags:
    - docker

test:
  stage: test
  script:
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./tests/tests.py ${DOCKERHOST:-localhost} 7357
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./python/scheduler_slurm.py --test --test_host ${DOCKERHOST:-localhost} --test_port 7357 --num_cpus 1
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./python/scheduler_local.py --time_limit 8 --time_window 3 --test --test_host ${DOCKERHOST:-localhost} --test_port 7357 --work_dir . --num_cpus 1
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - docker-compose -f test.yml stop
    - docker-compose -f test.yml rm -f
  tags:
    - docker
