before_script:
    - docker info
build_image:
    script:
        - docker-compose -f test.yml up --force-recreate -d
        - sleep 10
        - PYTHONPATH=$PWD/python:$PYTHONPATH python ./tests/tests.py ${DOCKERHOST:-localhost} 7357 test test test test
