before_script:
    - echo $USER
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - git clean -fdx
    - git reset --hard
    - docker-compose -f deployment/local/docker-compose.yml -p whiplash stop
    - docker-compose -f deployment/local/docker-compose.yml -p whiplash rm -f
    - docker-compose -f deployment/local/docker-compose.yml -p whiplash build
    - docker-compose -f deployment/local/docker-compose.yml -p whiplash up -d
    - sleep 40
    - docker logs whiplash_api_1
    - docker logs whiplash_scheduler_1
  tags:
    - docker

test:
  stage: test
  script:
    - export PYTHONPATH=$PWD/rte:$PYTHONPATH
    - ./tests/pre-tests.py localhost 1337
    - sleep 60
    - docker logs whiplash_scheduler_1
    - ./tests/post-tests.py localhost 1337
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - docker-compose -f deployment/local/docker-compose.yml -p whiplash stop
    - docker-compose -f deployment/local/docker-compose.yml -p whiplash rm -f
  tags:
    - docker
