before_script:
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - git clean -fdx
    - git reset --hard
    - docker-compose -f deployment/dev/docker-compose.yml build
    - docker-compose -f deployment/dev/docker-compose.yml up -d
    - sleep 30
  tags:
    - docker

test:
  stage: test
  script:
    - export PYTHONPATH=$PWD/rte:$PYTHONPATH
    - ./tests/pre-tests.py ${DOCKERHOST:-localhost} 1337
    - sleep 30
    - docker logs dev_rte_1
    - ./tests/post-tests.py ${DOCKERHOST:-localhost} 1337
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - docker-compose -f deployment/dev/docker-compose.yml stop
    - docker-compose -f deployment/dev/docker-compose.yml rm -f
  tags:
    - docker
