before_script:
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - docker-compose -f test.yml build
    - docker-compose -f test.yml up -d
    - sleep 30
  tags:
    - docker

test:
  stage: test
  script:
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./tests/tests.py ${DOCKERHOST:-localhost} 1337
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./python/scheduler_users.py --test --host ${DOCKERHOST:-localhost} --port 1337
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - docker-compose -f test.yml stop
    - docker-compose -f test.yml rm -f
  tags:
    - docker
