before_script:
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - docker-compose -f test.yml build
    - docker-compose -f test.yml up -d
    - sleep 30
  tags:
    - docker

test:
  stage: test
  script:
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./tests/pre-tests.py ${DOCKERHOST:-localhost} 1337
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./rte/create_token.py ${DOCKERHOST:-localhost} 1337 test test
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./rte/manager.py --local --host ${DOCKERHOST:-localhost} --port 1337 --num_cpus 1 --test
    - PYTHONPATH=$PWD/python:$PYTHONPATH ./tests/post-tests.py ${DOCKERHOST:-localhost} 1337
    - cat *.log
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - docker-compose -f test.yml stop
    - docker-compose -f test.yml rm -f
  tags:
    - docker
