before_script:
    - docker info

stages:
  - build
  - test
  - cleanup

build:
  stage: build
  script:
    - git clean -fdx
    - git reset --hard
    - cd deployment/dev
    - docker-compose build
    - docker-compose up -d
    - cd ../../
    - sleep 30
  tags:
    - docker

test:
  stage: test
  script:
    - export PYTHONPATH=$PWD/rte:$PYTHONPATH
    - ./tests/pre-tests.py ${DOCKERHOST:-localhost} 1337
    - sleep 30
    - docker logs whiplash_rte_1
    - ./tests/post-tests.py ${DOCKERHOST:-localhost} 1337
  tags:
    - docker

cleanup:
  stage: cleanup
  script:
    - cd deployment/dev
    - docker-compose stop
    - docker-compose rm -f
    - cd ../../
  tags:
    - docker
