site_name: Whiplash
docs_dir: docs
site_dir: www/html/docs
theme: flatly
pages:
- Home: index.md
- Overview: overview.md
- Deployment: deployment.md
- Standards: standards.md
- Usage: usage.md
- Snapshot: snapshot.md
- Examples: examples.md

