odb:
    extends:
        file: ../../odb/docker-compose.yml
        service: odb
api:
    extends:
        file: ../../api/docker-compose.yml
        service: api
rte:
    extends:
        file: ../../rte/docker-compose.yml
        service: rte
