db.createUser({user:"www",pwd:"7cJgeAkHdw{oktPNYdgYE3nJ",roles:[{role:"readWrite",db:"wdb"}]});
db.createUser({user:"api",pwd:"haYrv{Ak9UJiaDsqVTe7rLJTc",roles:[{role:"readWrite",db:"wdb"}]});
db.createUser({user:"pwn",pwd:"cftXzdrjheHEARuJKT39x]3sV",roles:[{role:"dbOwner",db:"wdb"}]});
db.createUser({user:"scheduler",pwd:"c93lbcp0hc[5209sebf10{3ca",roles:[{role:"read",db:"wdb"}]});
db.fs.files.createIndex({md5 : 1, "metadata.property_id" : 1, "metadata.owner" : 1},{unique : true});
db.executables.createIndex({name : 1, algorithm : 1, version : 1, build : 1, owner : 1},{unique : true});
db.properties.createIndex({input_model_id : 1, executable_id : 1, md5 : 1, owner : 1},{unique : true});
db.jobs.createIndex({name : 1, owner : 1, md5 : 1},{unique : true});
db.collaborations.createIndex({name : 1},{unique : true});
db.users.createIndex({username : 1},{unique : true});
db.clients.createIndex({name : 1},{unique : true});
db.setProfilingLevel(2);
