FROM whiplash/rte-local:build

COPY src /opt/wdb/src
WORKDIR /opt/wdb/src
RUN WDB_HOME=/opt/wdb make scheduler.driver worker.driver && make install
WORKDIR /opt/wdb/src/apps
RUN WDB_HOME=/opt/wdb sh build_apps.sh
WORKDIR /opt/wdb
