FROM php:5.6-apache
RUN a2enmod rewrite
RUN docker-php-ext-install mysql mysqli pdo pdo_mysql
RUN apt-get update
RUN apt-get install -y php5-dev php5-cli php-pear
RUN pecl install mongo
COPY www/config/php.ini /usr/local/etc/php/
COPY www /var/www/html
