FROM node
RUN apt-get update
RUN apt-get install -y libkrb5-dev
RUN apt-get install -y python-dev libyaml-dev python-pip
RUN pip install mkdocs

# building docs
WORKDIR /tmp
COPY docs /tmp/docs
RUN mv docs/mkdocs.yml . && mkdocs build

# building node
WORKDIR /src
COPY *.json /src/
RUN cd /src; npm install

# copy in node sources
COPY bin /src/bin
COPY logs /src/logs
COPY libs /src/libs

# finishing
WORKDIR /
EXPOSE 1337
